export const EXERCISES = [
  { name: "Figure en 8", cat: "h", color: "#ff3cac", desc: "Fais glisser la rondelle en forme de 8 devant toi, de gauche à droite, en alternant forehand et backhand. Genoux fléchis, bâton près du sol.", anim: "figure8" },
  { name: "Passe latérale sous le pont", cat: "b", color: "#00f5ff", desc: "Envoie la rondelle sous le petit pont de gauche à droite et reprends-la de l'autre côté. Reste stationnaire, contrôle la force.", anim: "bridge_lateral" },
  { name: "Dribble devant-arrière", cat: "h", color: "#f9f002", desc: "Pousse la rondelle devant toi puis tire-la vers toi en alternant les deux côtés du bâton. Rythme régulier, poignets souples.", anim: "frontback" },
  { name: "Slalom double pont", cat: "b", color: "#00f5ff", desc: "Envoie la rondelle sous le premier pont, récupère-la, envoie-la sous le second. Deux ponts alignés, flux continu.", anim: "slalom" },
  { name: "Croisé forehand/backhand", cat: "h", color: "#ff3cac", desc: "Frappe forehand vers la droite, reviens backhand vers la gauche rapidement. Simule un croisé de bâton devant toi.", anim: "crossover" },
  { name: "Pas chassé + puck devant", cat: "p", color: "#39ff14", desc: "Pas chassé latéral de 2-3 pas pendant que tu contrôles la rondelle devant toi. Les pieds bougent, les mains restent stables.", anim: "chasse_front" },
  { name: "Pont — entrée côté gauche", cat: "b", color: "#00f5ff", desc: "Glisse la rondelle sous le pont en entrant par le côté gauche, récupère à droite. Répète rapidement.", anim: "bridge_left" },
  { name: "Pont — entrée côté droit", cat: "b", color: "#00f5ff", desc: "Glisse la rondelle sous le pont en entrant par le côté droit, récupère à gauche. Répète rapidement.", anim: "bridge_right" },
  { name: "Déplacement latéral + puck", cat: "p", color: "#39ff14", desc: "Déplace-toi latéralement (2 pas à gauche, 2 à droite) tout en maintenant la rondelle devant toi à portée de bâton.", anim: "lateral_move" },
  { name: "Puck derrière le dos", cat: "h", color: "#b44aff", desc: "Fais passer la rondelle derrière ton dos, d'un côté à l'autre. Exercice de coordination avancé, penche légèrement le tronc.", anim: "behind_back" },
  { name: "Figure en 8 rapide", cat: "h", color: "#ff3cac", desc: "Même mouvement qu'au début mais à vitesse maximale. Accélère les poignets, maintiens le contrôle.", anim: "figure8" },
  { name: "Pont + pas croisé", cat: "b", color: "#00f5ff", desc: "Envoie la rondelle sous le pont et fais un pas croisé en la récupérant de l'autre côté. Coordonne pieds et mains.", anim: "bridge_cross" },
  { name: "Dribble rapide deux mains", cat: "h", color: "#f9f002", desc: "Dribble très vite en alternant forehand et backhand sur place. Pousse-tires rapides, amplitude réduite.", anim: "rapid_dribble" },
  { name: "Slalom double pont ×2", cat: "b", color: "#00f5ff", desc: "Deux ponts : fais passer la rondelle sous les deux de suite, reviens au départ. Flux continu sans perdre la rondelle.", anim: "slalom" },
  { name: "Reculons + puck latéral", cat: "p", color: "#39ff14", desc: "Recule doucement tout en faisant un contrôle latéral de la rondelle devant toi. Regard devant.", anim: "backward_lateral" },
  { name: "Passe sous le pont D/G", cat: "b", color: "#00f5ff", desc: "Passe la rondelle alternativement sous le pont de droite à gauche et de gauche à droite. Cadence soutenue.", anim: "bridge_lateral" },
  { name: "Saut latéral + puck devant", cat: "p", color: "#39ff14", desc: "Petit saut latéral d'un pied à l'autre pendant que tu pousses la rondelle devant toi. Atterris sur la plante des pieds.", anim: "lateral_jump" },
  { name: "Croisé forehand/backhand", cat: "h", color: "#ff3cac", desc: "Accélère le croisé de bâton : frappe fort à droite, reviens vite à gauche. Maintiens l'équilibre.", anim: "crossover" },
  { name: "Pont + virage 180°", cat: "b", color: "#ff6b00", desc: "Envoie la rondelle sous le pont, fais un pivot de 180° et récupère-la de l'autre côté. Pieds rapides au virage.", anim: "bridge_turn" },
  { name: "Figure en 8 + variation", cat: "h", color: "#ff3cac", desc: "Figure en 8 avec une extension plus large : agrandis le mouvement, teste ta portée maximale de chaque côté.", anim: "figure8" },
  { name: "Pas chassé + puck côté", cat: "p", color: "#39ff14", desc: "Pas chassé latéral avec la rondelle tenue sur le côté du corps, pas devant. Simule une sortie de zone.", anim: "chasse_side" },
  { name: "Pont — entrée arrière", cat: "b", color: "#00f5ff", desc: "Positionne-toi dos au pont et pousse la rondelle dessous à l'aveugle, puis pivote pour récupérer.", anim: "bridge_back" },
  { name: "Dribble devant-arrière rapide", cat: "h", color: "#f9f002", desc: "Version accélérée du dribble devant-arrière. Amplitude maximale, poignets explosifs.", anim: "frontback" },
  { name: "Slalom + pas croisé", cat: "b", color: "#00f5ff", desc: "Slalom sous deux ponts avec un pas croisé entre les deux passages. Coordonne tes enjambées.", anim: "slalom_cross" },
  { name: "Puck derrière le dos ×2", cat: "h", color: "#b44aff", desc: "Répète le passage derrière le dos, cette fois plus vite. Enchaîne 5 passages consécutifs si possible.", anim: "behind_back" },
  { name: "Reculons + pont", cat: "b", color: "#ff6b00", desc: "Recule vers le pont et envoie la rondelle dessous en reculant. Récupère-la en repartant vers l'avant.", anim: "bridge_back" },
  { name: "Croisé de bâton rapide", cat: "h", color: "#ff3cac", desc: "Maximum de croisés forehand/backhand en 20 secondes. Compte mentalement, dépasse ton record.", anim: "crossover" },
  { name: "Saut avant-arrière + puck", cat: "p", color: "#39ff14", desc: "Petit saut vers l'avant puis vers l'arrière pendant le contrôle de rondelle. Reste toujours en équilibre.", anim: "jump_frontback" },
  { name: "Figure en 8 relâchée", cat: "h", color: "#ff3cac", desc: "Figure en 8 à vitesse modérée pour récupérer. Concentre-toi sur la fluidité du poignet, pas la vitesse.", anim: "figure8" },
  { name: "Pont double + pas chassé", cat: "b", color: "#00f5ff", desc: "Double pont avec pas chassé latéral entre les deux. Combine déplacement et contrôle sous les ponts.", anim: "bridge_cross" },
  { name: "Passe latérale sous le pont", cat: "b", color: "#00f5ff", desc: "Retour aux passes latérales sous le pont. Essaie de battre ton rythme du début de session.", anim: "bridge_lateral" },
  { name: "Dribble circulaire", cat: "h", color: "#b44aff", desc: "Fais tourner la rondelle en cercle autour de toi, en alternant forehand et backhand. Reste au centre, pieds stables.", anim: "circular" },
  { name: "Slalom double pont ×3", cat: "b", color: "#00f5ff", desc: "Slalom sous deux ponts, mais enchaîne 3 fois de suite sans pause. Accélération progressive.", anim: "slalom" },
  { name: "Pas chassé + puck devant", cat: "p", color: "#39ff14", desc: "Reprends le pas chassé avec puck devant. À cette étape, maintiens l'intensité malgré la fatigue.", anim: "chasse_front" },
  { name: "Pont + virage 360°", cat: "b", color: "#ff6b00", desc: "Envoie la rondelle sous le pont, fais un pivot complet de 360° et récupère-la. Défi d'équilibre et vitesse.", anim: "bridge_turn" },
  { name: "Croisé + extension", cat: "h", color: "#ff3cac", desc: "Croisé de bâton avec une extension maximale de chaque côté — quasi-lunges latéraux. Force et mobilité.", anim: "crossover" },
  { name: "Reculons + puck latéral", cat: "p", color: "#39ff14", desc: "Reculons avec contrôle latéral, version accélérée. Garde la tête haute, ne regarde pas la rondelle.", anim: "backward_lateral" },
  { name: "Figure en 8 — explosion", cat: "h", color: "#ff3cac", desc: "Figure en 8 à vitesse maximale absolue pendant 20 secondes. Tout donner.", anim: "figure8" },
  { name: "Pont — entrée gauche rapide", cat: "b", color: "#00f5ff", desc: "Entrée côté gauche sous le pont, vitesse maximale. Répète autant de fois que possible.", anim: "bridge_left" },
  { name: "Saut latéral + puck devant", cat: "p", color: "#39ff14", desc: "Sauts latéraux avec puck — version intensive. Plus d'amplitude dans les sauts.", anim: "lateral_jump" },
  { name: "Puck derrière le dos — vitesse", cat: "h", color: "#b44aff", desc: "Passages derrière le dos à pleine vitesse. Finisseur de coordination avancée.", anim: "behind_back" },
  { name: "Slalom + pas croisé final", cat: "b", color: "#00f5ff", desc: "Dernier slalom avec pas croisé. Donne tout, c'est l'avant-dernier exercice.", anim: "slalom_cross" },
  { name: "Dribble rapide deux mains", cat: "h", color: "#f9f002", desc: "Avant-dernière série de dribbles rapides. Maintiens l'intensité jusqu'au bout.", anim: "rapid_dribble" },
  { name: "Pont double + pas chassé", cat: "b", color: "#00f5ff", desc: "Avant-dernier exercice : double pont avec pas chassé. Reste technique même fatigué.", anim: "bridge_cross" },
  { name: "Figure en 8 — FINISSEUR", cat: "h", color: "#ff3cac", desc: "DERNIER EXERCICE ! Figure en 8 à fond. Laisse tout sur le plancher !", anim: "figure8" },
];

export const CAT_LABEL = { h: "Mains", p: "Pieds + Mains", b: "Avec pont" };
export const CAT_COLOR = { h: "#ff3cac", p: "#39ff14", b: "#00f5ff" };
